In [2]:
import torch
x= (torch.rand(2,3,4)*100).int()
print(x)
print(x.shape)

tensor([[[11, 28, 30, 56],
         [23, 23, 98, 55],
         [19,  1, 85, 94]],

        [[56, 79, 49, 75],
         [66, 12,  5, 89],
         [10, 90, 64,  0]]], dtype=torch.int32)
torch.Size([2, 3, 4])


E:\sequence\sequence\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
y= (torch.rand(2,3,4)*100).int()
print(y)
print(y.shape)

tensor([[[42, 44, 24, 64],
         [63, 72, 99, 48],
         [78, 72, 19, 63]],

        [[84, 91,  8, 19],
         [57, 80, 30, 11],
         [47, 56, 18, 73]]], dtype=torch.int32)
torch.Size([2, 3, 4])


In [6]:
z_0 = torch.cat((x,y), dim=0)

In [7]:
print(z_0)

tensor([[[11, 28, 30, 56],
         [23, 23, 98, 55],
         [19,  1, 85, 94]],

        [[56, 79, 49, 75],
         [66, 12,  5, 89],
         [10, 90, 64,  0]],

        [[42, 44, 24, 64],
         [63, 72, 99, 48],
         [78, 72, 19, 63]],

        [[84, 91,  8, 19],
         [57, 80, 30, 11],
         [47, 56, 18, 73]]], dtype=torch.int32)


In [10]:
z_1 = torch.cat((x,y), dim=1)
print(z_1)

tensor([[[11, 28, 30, 56],
         [23, 23, 98, 55],
         [19,  1, 85, 94],
         [42, 44, 24, 64],
         [63, 72, 99, 48],
         [78, 72, 19, 63]],

        [[56, 79, 49, 75],
         [66, 12,  5, 89],
         [10, 90, 64,  0],
         [84, 91,  8, 19],
         [57, 80, 30, 11],
         [47, 56, 18, 73]]], dtype=torch.int32)


In [12]:
z_2 = torch.cat((x,y), dim=2)
print(z_2)

tensor([[[11, 28, 30, 56, 42, 44, 24, 64],
         [23, 23, 98, 55, 63, 72, 99, 48],
         [19,  1, 85, 94, 78, 72, 19, 63]],

        [[56, 79, 49, 75, 84, 91,  8, 19],
         [66, 12,  5, 89, 57, 80, 30, 11],
         [10, 90, 64,  0, 47, 56, 18, 73]]], dtype=torch.int32)
